### ISSUE TITLE
Defects due to unsigned comparison with 0

### ISSUE THREAD

**Issue by ikolev21** [bitwizeshift/string_view-standalone#2]
Thank you for this implementation.

Clang issues 4 warnings about comparing an unsigned to 0, these are on lines 285, 332, 424 and 515 in detail/string_view.inl. These are all valid, the code passes tests because the character comparisons inside the loops fail and the loops exit, however, the comparisons access memory outside the allowed ranges and might cause access violation.

**Comment by zimmerle** [comment]
#5 may fix some of the warnings.
