### ISSUE TITLE
substr() throws if pos == size

### ISSUE THREAD

**Issue by AdmiralCurtiss** [bitwizeshift/string_view-standalone#3]
For example:

~~~
    string_view x("abc");
    string_view y = x.substr(3);
    ASSERT_TRUE(y == "");
~~~

I would expect an empty string to be returned.
Compare https://en.cppreference.com/w/cpp/string/basic_string_view/substr

**Comment by eyalroz** [comment]
@AdmiralCurtiss : Have you thought about forking this repo and fixing this yourself? It looks like it hasn't been touched in 3 years.
